### ISSUE TITLE
docgen running slow

### ISSUE THREAD

**Issue by webratz** [cdklabs/jsii-docgen#680] opened 2022-05-06 07:19 UTC
version "6.3.23"

running `jsii-docgen` on my CDK libary project takes about 1.04 minutes The project itself isn't very big, it has some external dependencies though.
I'm wondering if that is expected, and if not, what would be a good way to figure out why it takes so long. 

I have created a flame graph, and it seems to spend lot of time in copy.js and glob.js which hints to FS operations. (I can share the underlying data, its just too big to upload here)

![Screenshot 2022-05-06 at 09 17 58](https://user-images.githubusercontent.com/2162832/167085338-2d030355-a0fb-461f-b9bd-826630f3c76a.png)

**Comment by agdimech** [comment] 2022-05-21 12:54
I believe it copies the entire tree (including node_modules) instead of operating in place. This would explain why it takes so long as it is busy copying files.

**Comment by webratz** [comment] 2022-05-30 11:23
is this intended behaviour, or just something that happens accidentally?

**Comment by agdimech** [comment] 2022-06-17 00:09
It was intentional however this PR will remove that logic and will significantly improve performance by ~ 6X:

https://github.com/cdklabs/jsii-docgen/pull/644

**Comment by agdimech** [comment] 2023-04-18 20:59
PR has been merged so this can be closed now.

**Comment by mrgrain** [comment] 2024-06-10 09:32
Closing since this was reported for a very old version. For people still experiencing "slowness" please open a new issue including some numbers, expectations and ideal flame graphs or reproductions. Thank you.

**Closed by mrgrain** 2024-06-10 09:32 UTC
